### ISSUE TITLE
100mBTC Bounty - Support Data labels

### ISSUE THREAD

**Issue by mkouba** [timmolter/XChart#106]
Is it possible to show the data labels (i.e. `y` data values)? It would be great if it was possible for some types of charts (bar, area, ...).

**Comment by timmolter** [comment]
I've added a feature request tag. Good idea.

**Comment by Chris-Cullins** [comment]
Hi, I'm a developer and am interested in working on this issue (At the very least looking into it heavily). I'm not sure if you're assigning issues to people, so I figured I'd comment to let you know I'm interested.

**Comment by timmolter** [comment]
Great! No one else is working on it that I know of, so it's all yours!

**Comment by Chris-Cullins** [comment]
Just to get a clarification (and make sure I'm not doing the wrong thing) is the request for the ability to have data labels, like those that are on Chart_Pie (The shown percentages on each slice), on other charts types?

Wanting to make sure I get what we're asking for here, brand new to this project!

**Comment by mkouba** [comment]
@Chris-Cullins Yep, I was particularly interested in Bar charts (Chart_Category). Good to see someone working on the issue!

**Comment by timmolter** [comment]
@Chris-Cullins Yes, good to get clarification first! Sorry, I should have added the specifics beforehand.

I was imagining that the data labels would work like on these plots: <https://bitcoinium.com/split>. When you hover over the data point, a box comes up with the X,Y data. The box should have the smarts so that when it's by the edge of the chart it auto-positions itself optimally, i.e. doesn't draw outside of the plot. So it's like a tooltip, that pops up when hovering over the marker.

I think the style attributes should be:

1. shouldShowDataLabels
1. dataLabelsAsToolTips (either they are all rendered permanently or on via pop up)
1. {enum} dataLabelContent: [Xlabels, yLabels, xAndYLabels

For pie charts, someone might disable all annotations and rather have the annotation popup when hovering over the pie slice.

This is all open for discussion.

**Comment by mkouba** [comment]
@timmolter Hm, and what about charts exported as bitmaps?

**Comment by timmolter** [comment]
@mkouba the labels will only appear on the bitmap if the user chose `dataLabelsAsToolTips = false`, i.e. permanently on the chart.

**Comment by mkouba** [comment]
@timmolter Ok, excellent.

**Comment by on247** [comment]
I want to work in this one ?

**Comment by Chris-Cullins** [comment]
Yeah, unfortunately I haven't had the time required to dig into it, work has been crazy this last month. Feel free!

**Comment by joshafest** [comment]
well if i get somthing from another stack chart ........i will do it also...

**Comment by hakantkn** [comment]
I want to work on this issue.
