### ISSUE TITLE
Can't change line width

### ISSUE THREAD

**Issue by andreyon** [timmolter/XChart#152]
Hi!
I writing:
`XYSeries series = getChart().addSeries(title, ChartUpdater.getXPoints(), ChartUpdater.getYPoints());`
        `series.setLineColor(lineColor);`
       `series.setMarkerColor(lineColor);`
       `series.setLineWidth(8.0F);`
       `chartPanel.updateUI();`

All works fine, but line width does not changing.
Thanx!

**Comment by timmolter** [comment]
It's working for me. What version are you using?

**Comment by andreyon** [comment]
xchart 3.0.3

**Comment by timmolter** [comment]
Please provide a demo class showing the problem. I cannot repeat the issue on my end.

**Comment by andreyon** [comment]
There are link to Idea project: https://drive.google.com/open?id=0B7bKSJPuY1XyRkFNSUR4NmdhWlk
I tryed to change line width in LineBoldEventListener.

**Comment by timmolter** [comment]
I don;t think calling updateUI is going to do anything. Try calling `updateSeries` on the `XChartPanel `instance. Rather than removing the series every time and replacing it, just update the data. Also keep a reference to the original series and switch the line width on it before calling `updateSeries`.
