### ISSUE TITLE
NaNs aren't handled correctly on the Y axis

### ISSUE THREAD

**Issue by 33d** [timmolter/XChart#243]
I've been using NaNs in series to represent where I don't have data on the X axis, but if the series starts with NaN, an extra point appears at the start.

This sample should show one point at (2.0, 1.0), but an extra point appears at (1.0, 1.0):

```
import org.knowm.xchart.QuickChart;
import org.knowm.xchart.SwingWrapper;
import org.knowm.xchart.XYChart;
import org.knowm.xchart.style.markers.Circle;

public class Bug {

	public static void main(String[] args) throws Exception {

		double[] xData = new double[] { 1.0, 2.0 };
		double[] yData = new double[] { Double.NaN, 1.0 };

		// Create Chart
		XYChart chart = QuickChart.getChart("Sample Chart", "X", "Y", "1", xData, yData);

		chart.getSeriesMap().get("1").setMarker(new Circle());

		// Show it
		new SwingWrapper(chart).displayChart();

	}
}
```

Changing `PlotContent_XY:107` from `if (next == NaN)` to `if (Double.isNaN(next))` seems to fix the problem.

**Comment by Aklakan** [comment]
For the same issue in
https://github.com/timmolter/XChart/blob/develop/xchart/src/main/java/org/knowm/xchart/internal/chartpart/AxisTickCalculator_Number.java#L146

I just ran into the exception 

```
NumberFormatException caused by this number: NaN
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.knowm.xchart.internal.chartpart.AxisTickCalculator_Number.calculate(AxisTickCalculator_Number.java:170)
```

The reason is again a `==` comparision to Double.NaN instead of `Double.isNaN(...)`. Please fix all instances of these incorrect comparisons. NaN always compares false to NaN.

**Comment by timmolter** [comment]
ok, i'll fix it soon. Thanks!

**Comment by timmolter** [comment]
Fixed.
